# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.7
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_listener', [dirname(__file__)])
        except ImportError:
            import _listener
            return _listener
        if fp is not None:
            try:
                _mod = imp.load_module('_listener', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _listener = swig_import_helper()
    del swig_import_helper
else:
    import _listener
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


def _swig_setattr_nondynamic_method(set):
    def set_attr(self,name,value):
        if (name == "thisown"): return self.this.own(value)
        if hasattr(self,name) or (name == "this"):
            set(self,name,value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr



def listener_make_clock_recovery(*args):
  return _listener.listener_make_clock_recovery(*args)
listener_make_clock_recovery = _listener.listener_make_clock_recovery
class listener_clock_recovery(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _listener.delete_listener_clock_recovery
    __del__ = lambda self : None;
listener_clock_recovery_swigregister = _listener.listener_clock_recovery_swigregister
listener_clock_recovery_swigregister(listener_clock_recovery)


def listener_make_tag_monitor(*args):
  return _listener.listener_make_tag_monitor(*args)
listener_make_tag_monitor = _listener.listener_make_tag_monitor
class listener_tag_monitor(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _listener.delete_listener_tag_monitor
    __del__ = lambda self : None;
    STATE_PTR = _swig_property(_listener.listener_tag_monitor_STATE_PTR_get, _listener.listener_tag_monitor_STATE_PTR_set)
    def get_tag_log(self): return _listener.listener_tag_monitor_get_tag_log(self)
listener_tag_monitor_swigregister = _listener.listener_tag_monitor_swigregister
listener_tag_monitor_swigregister(listener_tag_monitor)


def listener_make_reader_monitor_cmd_gate(*args):
  return _listener.listener_make_reader_monitor_cmd_gate(*args)
listener_make_reader_monitor_cmd_gate = _listener.listener_make_reader_monitor_cmd_gate
class listener_reader_monitor_cmd_gate(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _listener.delete_listener_reader_monitor_cmd_gate
    __del__ = lambda self : None;
    def get_reader_log(self): return _listener.listener_reader_monitor_cmd_gate_get_reader_log(self)
listener_reader_monitor_cmd_gate_swigregister = _listener.listener_reader_monitor_cmd_gate_swigregister
listener_reader_monitor_cmd_gate_swigregister(listener_reader_monitor_cmd_gate)



